### PR TITLE
bottomless: move to sqld/ tree

### PR DESCRIPTION
**Pull request by psarna**
libSQL's bottomless S3 replication is going to live in the sqld/ tree, so the project is moved as is from https://github.com/libsql/bottomless/. After it's merged, I'll archive libsql/bottomless and redirect to sqld/

/cc @glommer

### CODE REVIEW

**Comment by psarna** [comment]
note: bottomless historically had its own `ffi.rs` with bindings, which is now redundant, because sqld also has it. Also, all the i8 and u8 pointers need to be translated to c_char to avoid compilation issues between architectures. I'll work on all that in this pull request

**Comment by penberg** [comment]
@psarna looks good, please ping me when it's not draft, and let's merge

**Review by penberg — APPROVED** [review]

**Comment by psarna** [comment]
Once merged, I'll work on a follow-up that migrates bottomless to the new ffi interface, generated from libsqlite3-sys. That's a formality, but it's better to do it sooner than later to avoid bit rot

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
@psarna this is odd, and I have no log, I'll just retry

bors try

**Comment by MarinPostma** [comment]
@psarna I'm not sure what's going on with ci, other prs seem to go in just fine?

**Comment by MarinPostma** [comment]
bors try

**Comment by MarinPostma** [comment]
bors try

**Comment by psarna** [comment]
bors try

**Comment by psarna** [comment]
bors merge

**Pull request merged**
