### PR TITLE
libsql-client: Fix transaction() to be transactional

### LINKED ISSUE #93: Multiple statements should be wrapped in an implicit transaction in sqld
As discussed today, we should add a transaction to the batch of statements.

### PR DESCRIPTION
**Pull request by penberg**
Fixes #93

### CODE REVIEW

**Review by MarinPostma — APPROVED** [review]
bors merge

**Comment by penberg** [comment]
@MarinPostma this is now in `main`, yet bors kept the pull request open?

**Comment by MarinPostma** [comment]
@penberg yeah I'm trying to figure out what's going on. It looks like github it preventing bors from marking the PR as merged, maybe is that related to the settings I have changed?

**Comment by MarinPostma** [comment]
closing manually

**Pull request closed without merging**
