### PR TITLE
Correctly report errors when executing statements over Hrana

### LINKED ISSUE #453: Hrana v2: unexpected empty response for an invalid query?
I played with Hrana v2 specification a little to get a feel of it before implementing its support in https://github.com/libsql/libsql-client-rs, and I think I found unexpected behavior. When I curl the following payload to my local sqld instance, with POST method, to endpoint `localhost:8080/v2/pipeline`:
```json
{
    "baton": null,
    "requests": [
        {
            "type": "execute",
            "stmt": { "sql": "insert into nonexistent values (42)" }
        }
    ]   
}
```
, then it returns an empty response instead of an error that explains that table `nonexistent` does not exist, as it used to happen before. If the table exists, this query properly returns an ack. Is it a regression?

/cc @honzasp

### PR DESCRIPTION
**Pull request by honzasp**
Fixes #453

### CODE REVIEW

**Comment by honzasp** [comment]
Clippy seems to complain about unrelated code :( I'm not sure how to proceed? Should I open another PR to try to fix the unrelated code?

**Comment by MarinPostma** [comment]
Yeah new rust version https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html

**Comment by MarinPostma** [comment]
Just fix it here I guess

**Comment by honzasp** [comment]
But `sqld` specifies 1.69.0 toolchain explicitly in `rust-toolchain.toml`, so perhaps the Github action does not honor this setting?

**Comment by MarinPostma** [comment]
It does not indeed

**Pull request merged**
