### PR TITLE
parse multiline when loading dump

### PR DESCRIPTION
**Pull request by glommer**
SQLite dumps are often multi-line, so accumulate on a buffer and only send when the line ends with ;

### CODE REVIEW

**Review by psarna — CHANGES_REQUESTED** [review]
Pretty sure it won't work, `rusqlite` will only execute the first statement on `execute()`. You probably want to use `execute_batch()` instead, in line 97: https://docs.rs/rusqlite/latest/rusqlite/struct.Connection.html#method.execute_batch, which is syntactic sugar that lets you split statements. It only works for statements without params, but we're only using text statements here, so it will work.

And while at it, consider renaming `line` to something like `statements`? It's no longer a single line which makes the code rather confusing. `curr` is what's actually a single line of code in the new form.

**Comment by glommer** [comment]
there's only a single statement, @psarna.
I am not sending more than one statement per execute, I am buffering the statement in case it is multiline.

**Comment by psarna** [comment]
ah! My bad

**Comment by glommer** [comment]
yes, we are. (sqlite generates them like that).
Although I was surprised to see multiline already anyway

**Comment by psarna** [comment]
bors merge

**Pull request merged**
