### PR TITLE
export sqlite3 dump

### PR DESCRIPTION
**Pull request by MarinPostma**
This PR ports the dumping loginc from sqlite to sqld. It allows the dumping of sqld tables to a sqlite compatible format.

sqld now exposes a CLI interface to export dumps, eg:

- print the dump for the database at the default path (`data.sqld`) to stdout:
```
sqld dump
```

- print the dump for the database at the path specified by `--db-path`:
```
sqld --db-path some/path/to/database dump
```

- write the dump for the database at the path specified by `--db-path` at the path specified by path:

```
sqld --db-path some/path/to/database dump --path write/dump/here
```

`dump` is a subcommand, so any argument passed after the `dump` have dump as subject, and any argument passed before `dump` have `sqld` as subject. Any argument with `sqld` as subject other than `--db-path` is ignored.

### CODE REVIEW

**Comment by MarinPostma** [comment]
@psarna requesting you for review on this one, since it's sqlite related

**Comment by MarinPostma** [comment]
@athoscouto FYI

**Review by psarna — APPROVED** [review]
Looks good (I *really* hope I didn't miss anything in the port from C)

**Comment by MarinPostma** [comment]
@psarna this is how we do it now, but it makes the images more complex... and we wanted to build other nice features on top of that, such as automatic migration etc, which makes if much more convenient. Another alternative is to move the dump code from shell.c to the libsql API?

**Comment by MarinPostma** [comment]
> @psarna this is how we do it now, but it makes the images more complex... and we wanted to build other nice features on top of that, such as automatic migration etc, which makes if much more convenient. Another alternative is to move the dump code from shell.c to the libsql API?

**Comment by MarinPostma** [comment]
bors merge

**Pull request merged**
