### PR TITLE
fix param support in proxy mode

### LINKED ISSUE #123: Param binding silently fails in HTTP query to DB replica
The values of query parameters are not bound to the query, when the query is sent to a DB replica.

Version:
```
version: 0.1.0
commit SHA: 1ff0f63a60c350e50f5d8831f7cc8bcd330f59e6
build date: 2023-01-27
```

Steps to reproduce:

- Run `sqld` primary on `:8080` and a replica on `:8081`
   - `sqld --grpc-listen-addr=0.0.0.0:5001 --http-listen-addr=0.0.0.0:8080`
   - `sqld --pg-listen-addr 127.0.0.1:5433 --primary-grpc-url http://127.0.0.1:5001 --http-listen-addr=0.0.0.0:8081` (make sure to run in a different folder or set a different DB file)
- Setup the table: `curl localhost:8080/ -d '{"statements":["CREATE TABLE user (id INTEGER PRIMARY KEY, name TEXT NOT NULL);"]}'`
- Insert into main DB: 
```
curl localhost:8080/ -d '{"statements":[{ "q": "INSERT INTO user (name) VALUES(:name);", "params": { ":name": "main" } }]}' 
# works!
```
- Fail to insert into replica:
```
curl localhost:8081/ -d '{"statements":[{ "q": "INSERT INTO user (name) VALUES(:name);", "params": { ":name": "replica" } }]}'
# query fails with error:
# [{"error":{"message":"missing parameters, expected 1 found 0"}}]
```

### PR DESCRIPTION
**Pull request by MarinPostma**
This PR fixes the bug caused by params not being implemented for proxy mode sqld.

close #123

### CODE REVIEW

**Comment by athoscouto** [comment]
The code looks good and fixes the issue.

**Comment by MarinPostma** [comment]
Can you approve @athoscouto so I can merge?

**Comment by athoscouto** [comment]
I can't, don't have write permission.

**Review by penberg — APPROVED** [review]

**Comment by penberg** [comment]
bors merge

**Pull request merged**
